import Foundation

/// Tool definitions and system prompt for the chat loop, sourced from the
/// embedded crrdb-mcp library itself — single source of truth shared with the
/// desktop MCP server.
enum AtmanTools {

    static var systemPrompt: String {
        basePrompt + "\n\nToday is \(todayString)."
    }

    private static var todayString: String {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "yyyy-MM-dd (EEEE)"
        return formatter.string(from: Date())
    }

    private static let basePrompt: String = """
        You are Atman Agent, a personal data assistant backed by a SQLite database stored \
        on the user's phone. Each user table is a "sub-app": a small schema the user \
        creates by chatting (e.g. car_fuel_history, workouts, expenses). Sub-apps can \
        later be shared with friends, so schemas must stay replication-friendly.

        \(Crrdb.shared.instructions())

        Keep responses focused, brief, and concise. After completing writes, \
        confirm in one short sentence what was stored.

        Formatting: you are rendering into a narrow mobile chat. Markdown \
        tables, code blocks, and headings are supported, but rows are usually \
        too long for a table on a phone — prefer compact lines: one line per \
        record, key figures in bold, e.g. \
        "**2025-06-12** · 42.0 L · ₩120,000 — S-Oil Busan". Use a table only \
        when it stays narrow (3 columns or fewer, short cells).
        """

    /// Extra guardrails for the small on-device model (lessons from the
    /// Qwen3-4B spike: it stalls into ask-permission mode and forgets SQL
    /// conventions without explicit rules).
    static var localSystemPrompt: String {
        systemPrompt + """


        IMPORTANT rules:
        - Act immediately using tools. Never ask for permission or confirmation; \
        do it and report the result in one short sentence.
        - create_table SQL MUST end with `) STRICT`, MUST include `_raw TEXT NOT NULL` \
        and `_said_at TEXT NOT NULL`, and MUST have a PRIMARY KEY \
        (use `id TEXT PRIMARY KEY` holding a 26-char ULID if unsure).
        - Only commit records when the user's message contains actual data. A message \
        that merely asks to start tracking creates the table only.
        - NEVER invent records. Values appearing in these instructions (dates, \
        litres, stations, "Morning run") are formatting samples, not data — \
        committing them corrupts the user's database.
        - Use only table names that get_schema returned. Never guess or shorten \
        a table name.
        - When a tool returns an error, fix the input per the hint and call the tool \
        again immediately. Never describe the fix in text instead of doing it.
        """
    }

    /// OpenAI-style tool specs for the local model (MLX ChatSession format).
    static var toolSpecs: [[String: any Sendable]] {
        definitions.map { def in
            [
                "type": "function",
                "function": [
                    "name": def["name"] as? String ?? "",
                    "description": def["description"] as? String ?? "",
                    "parameters": sendableValue(def["input_schema"] ?? [:]),
                ] as [String: any Sendable],
            ]
        }
    }

    private static func sendableValue(_ value: Any) -> any Sendable {
        switch value {
        case let dict as [String: Any]:
            var out: [String: any Sendable] = [:]
            for (key, inner) in dict { out[key] = sendableValue(inner) }
            return out
        case let array as [Any]:
            return array.map { sendableValue($0) }
        case let string as String:
            return string
        case let number as NSNumber:
            if CFGetTypeID(number) == CFBooleanGetTypeID() { return number.boolValue }
            if CFNumberIsFloatType(number) { return number.doubleValue }
            return number.intValue
        default:
            return String(describing: value)
        }
    }

    /// Anthropic Messages API `tools` array, generated by crrdb-mcp from the
    /// same rmcp router that serves MCP clients.
    static let definitions: [[String: Any]] = {
        guard let data = Crrdb.shared.toolDefinitions().data(using: .utf8),
              let array = (try? JSONSerialization.jsonObject(with: data)) as? [[String: Any]] else {
            fatalError("crrdb-mcp returned invalid tool definitions")
        }
        return array
    }()
}
